# Generated by Django 4.2.7 on 2025-02-21 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driving_license_number',
            field=models.CharField(help_text='Format: XX00 0000 0000000', max_length=16, validators=[django.core.validators.RegexValidator('^[A-Z]{2}\\d{2} ?\\d{4} ?\\d{7}$', 'Driving License must be in format: XX00 0000 0000000')]),
        ),
    ]
